
# gpu-context=wayland
# hwdec=auto-copy
# hwdec=no
vo=gpu-next
# ao=pipewire
# gpu-context=wayland
# profile=gpu-hq
# hwdec=auto
# hwdec=yes
# profile=high-quality
# profile=high-quality
# gpu-api=opengl
# profile=gpu-hq


# ## my tscale config
# video-sync=display-resample
# interpolation=yes
# scale=catmull_rom
# tscale=catmull_rom
# deband=yes 
# # tscale=box
# # tscale-window=quadric
# # tscale-clamp=0.0
# # tsca e-radius=1.025
#
# tscale=sphinx
# tscale-blur=0.6991556596428412

#############################################################
### From Github https://github.com/Tsubajashi/mpv-settings
#############################################################

###### Debanding
# deband=yes
# deband-iterations=4
# deband-threshold=35
# deband-range=16
# deband-grain=4

# ###### Luma up (uncomment one shader line only)	See: https://artoriuz.github.io/blog/mpv_upscaling.html
# glsl-shader="~~/shaders/ravu-zoom-ar-r3-rgb.hook"		# good balance between performance and quality
# scale=ewa_lanczos
# scale-blur=0.981251
#
# ###### Luma down (optional, uncomment shader line if your hardware can support it)
# dscale=catmull_rom
# correct-downscaling=yes
# linear-downscaling=no
#
###### Chroma up + down (optional, uncomment one shader line only if your hardware can support it)
# glsl-shader="~~/shaders/JointBilateral.glsl"
# glsl-shader="~~/shaders/FastBilateral.glsl"
# glsl-shader="~~/shaders/CfL_Prediction.glsl"
# cscale=lanczos
# sigmoid-upscaling=yes
#
# ###### Interpolation
# video-sync=display-resample
# interpolation=yes
# tscale=sphinx
# tscale-blur=0.6991556596428412
# tscale-radius=1.05
# tscale-clamp=0.0

#############################################################
#############################################################

# Audio normdlization settings
#
# af=lavfi=[loudnorm=I=-16:TP=-3:LRA=4] # from a random reddit enjoyer
af=lavfi=[loudnorm=I=-14:LRA=1:tp=-1]



volume=50
# af=lavfi=[dynaudnorm=f=75:g=25:p=0.55]
force-window=yes
window-dragging=no
# hidpi-window-scale=yes
auto-window-resize=no
keepaspect-window=no
loop=yes
loop-playlist=inf
image-display-duration=6
reset-on-next-file=video-pan-x,video-pan-y,panscan,video-align-x,video-align-y,video-rotate,video-zoom,ab-loop-a,ab-loop-b,speed
# reset-on-next-file=video-pan-x,video-pan-y,panscan,video-align-x,video-align-y,video-rotate,video-zoom,ab-loop-a,ab-loop-b,brightness,contrast,gamma,saturation,hue

screenshot-directory=/home/nightlyte/Pictures/mpv-screenshots/

[input-test]
loop=yes
input-test
force-window
idle
