############################################
# Video Settings
############################################
vo=gpu-next

## HDR to SDR 
# tone-mapping=st2094-40

## Hardware Decoding
# hwdec=yes

## Enabling this can sometimes fix freezes/glitches if using hwdec
# gpu-context=wayland

## Nvidia drivers on linux sometimes have issues decoding using Vulcan, so forcing gpu-api to use OpenGL can help in certain situations
# gpu-api=opengl

# profile=high-quality
# profile=gpu-hq


## my config for interpolating frames when slowing video speed
# video-sync=display-resample
# interpolation=yes
# scale=catmull_rom
# tscale=catmull_rom
# deband=yes 

############################################
# Audio Settings
############################################

## Specify audio output device -- uncomment if having crashes/audio issues/Wayland issues
# ao=pipewire

## Default starting volume
volume=50

## Audio normalization
### 2026-08-09 - currently beta testing this configuration from an epic chungus redditor
af=lavfi="pan=stereo|c0=FC+LFE+FL+BL+SL|c1=FC+LFE+FR+BR+SR,loudnorm=I=-14:LRA=1:tp=-1:linear=false:dual_mono=true"

### Other random normalization variations I found on le reddit
# af=lavfi=[loudnorm=I=-14:LRA=1:tp=-1]
# af=lavfi=[loudnorm=I=-16:TP=-3:LRA=4]
# af=lavfi=[dynaudnorm=f=75:g=25:p=0.55]


############################################
# Window Settings
############################################

## Settings for Wayland
force-window=immediate
autofit-smaller=1000x1000
window-dragging=no
auto-window-resize=no
keepaspect-window=no
# hidpi-window-scale=yes

############################################
# Playback
############################################

loop=yes
# loop=no
loop-playlist=inf
image-display-duration=6
reset-on-next-file=video-pan-x,video-pan-y,panscan,video-align-x,video-align-y,video-rotate,video-zoom,ab-loop-a,ab-loop-b,speed
# reset-on-next-file=video-pan-x,video-pan-y,panscan,video-align-x,video-align-y,video-rotate,video-zoom,ab-loop-a,ab-loop-b,brightness,contrast,gamma,saturation,hue

############################################
# General
############################################

screenshot-directory=~/Pictures/mpv-screenshots

############################################
# Profiles
############################################

[input-test]
loop=yes
input-test
force-window
idle

[audio-only]
profile-cond=(filename:match"%.mp3$" or filename:match"%.wav$") ~= nil
profile-restore=copy
af=
volume=100

[HDR]
profile-cond=p["video-params/gamma"] == "pq"
profile-restore=copy
tone-mapping=bt.2446a
gamut-mapping-mode=auto
hdr-compute-peak=yes
target-peak=100
target-trc=bt.1886
target-prim=bt.2020
