# /etc/keyd/default.conf
[ids]

*

# Logitech USB Receiver (Logitech Ergo Wave Keyboard)
# 046d:c548:07559210

[main]

# Creates a layer for the capslock key
capslock = layer(capslock)

# Indicates start of "capslock" layer while also remapping it to the Meta key with ":M"
[capslock:M]

### Meta+{keys below} keybind remaps

# Universal Clipboard
c = C-insert
v = S-insert


# # HHKB Pro Hybrid Type-S
# leftmeta = alt
# leftcontrol = meta
# leftalt = control
