# /etc/keyd/razernagav2pro.conf
[ids]
#################
# Razer Naga V2 Pro (Wireless - USB Dongle)
#################
# Keypad
1532:00a8:58ecc9da
# Mouse
1532:00a8:689c585f

#################
# Razer Naga V2 Pro Keypad (Wired)
#################
1532:00a7:58ecc9da

[main]
# #################
# # General
# #################
# 2 = layer(meta)
# 3 = layer(control)
#
# ### Navigate Forward/Backward (Browsers, Apps)
# 1 = A-right
# 4 = A-left
#
# ### Minimize Window
# - = M-pagedown
#
# ### Close Window
# = = M-q
#
# #################
# # PlasmaZones
# #################
#
# ### Cycle Window Forward/Backward in Zone
# 5 = M-A-.
# 8 = M-A-,
# ### Layout Picker
# 6 = M-A-space
# ### Move Window Left/Right
# 7 = M-A-S-left
# 9 = M-A-S-right
# ### Window to Next Desktop
# 0 = M-A-l


#################
# (Old) KDE Plasma with KZones Keybinds
#################
0 = C-A-up
1 = A-right
2 = layer(meta)
3 = layer(control)
4 = A-left
5 = C-A-d
# 6 = layer(control+meta)
6 = M-S-left
7 = C-A-left
8 = M-pagedown
9 = C-A-right
# - =
= = M-q
